variables:
  REPOSITORY: "xxxxxxxxxx.dkr.ecr.ap-northeast-2.amazonaws.com"
  IMAGE_NAME: "$REPOSITORY/$CI_PROJECT_NAME"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: docker:stable
services:
  - docker:dind

cache:
  paths:
    - .m2/repository/
stages:
  - build
  - package
  - deploy

build:
  image: maven:3.3-jdk-8
  stage: build
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*SNAPSHOT.jar

package:
  stage: package
  script:
    - docker info
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - docker build -t $IMAGE_NAME:${CI_COMMIT_SHA} .
    - $(aws ecr get-login --no-include-email --region ap-northeast-2)
    - docker push $IMAGE_NAME:${CI_COMMIT_SHA}
  tags:
    - dind

deploy_dev:
  stage: deploy
  image: alpine
  only:
    - master
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/_PROJECT_NAME/$CI_PROJECT_NAME/" deployment.yaml service.yaml
    - sed -i "s/_REPOSITORY/$REPOSITORY/" deployment.yaml service.yaml
    - sed -i "s/_VERSION/${CI_COMMIT_SHA}/" deployment.yaml service.yaml
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml